export interface Titular {
  assentamento: string,
  selagemAtual: string,
  selagemAntiga: string,
  nomeResponsavel: string,
  numeroCartaoCidadao: string,
  numeroCPF: string,
  dataNascimento: string,
  genero: number,
  racaEtinia: number,
  escolaridade: number,
  deficiencia: string,
  estadoCivil: number,
  rendaTotal: number,
  familiaNoProcessoHabitacional: number,
  familiaPorDomicilio: number,
  tempoMoradiaBairro: number,
  tempoMoradiaLouveira: number,
  possuiImovel: number,
  localImovel: string,
  jaContemplado: number,
  programaContemplado: string,
  contempladoNoPais: number,
  programaContempladoPais: string,
  ondeProgramaContempladoPais: string
}
