export interface Titular {
  id: string,
  assentamento: string,
  numeroSelagemAtual: string,
  numeroSelagemAntiga: string,
  nomeResponsavel: string,
  numeroCartaoCidadao: string,
  numeroCPF: string,
  dataNascimento: string,
  genero: number,
  etnia: number,
  escolaridade: number,
  deficiencia: string,
  estadoCivil: number,
  rendaTotal: number,
  familiaIncProcHabit: number | boolean,
  familiaPorDomicilio: number,
  tempoMoradiaBairro: number,
  tempoMoradiaLouveira: number,
  possuiImovel: number | boolean,
  qualLocalDoImovel: string,
  programaHabitacional: number | boolean,
  qualProgHabitacional: string,
  regFundOuUsocapiao: number | boolean,
  qualRegFundOuUsocapiao: string,
  aondeRegFundOuUsocapiao: string
}
