export interface Moradia {
  assentamento: string,
  numeroSelagemAtual: string | number,
  numeroSelagemAntiga: string | number,
  endereco: string,
  numero: string | number,
  complemento: string,
  bairro: string,
  familiaTemCadastroUnico: number | boolean,
  familiaAcessaUnidadeBasicaSaude: string,
  qualUnidadeBasicaSaude: string,
  familiaAcessoEscolas: number | boolean,
  utilizaTransporteEscolar: number | boolean,
  familiaAcessaCRAS: number | boolean,
  familiaAcessaCREAS: number | boolean,
  familiaAcessaServicosConvivenciaCrianca: number | boolean,
  familiaAcessaServicosConvivenciaIdosos: number | boolean,
  moradia: number,
  quantidadeBanheiros: number,
  quantidadeComodos: number,
  tipoMoradiaOcupada: number,
  caracteristicasCasa: number,
  acessoEnergiaEletrica: number,
  acessoAbastecimentoAgua: number,
  acessoSaneamentoSanitario: number,
  possuiAutomoveis: number,
  moradiaSofreuDesastre: number,
  usoMoradia: number,
  cachorro: number,
  gato: number,
  passaro: number,
  outroAnimal: number,
  energiaEletrica: number,
  aguaEsgoto: number,
  gastoAlimentacao: number,
  gastoMedicamentos: number,
  totalDespesas: number,
  observacoes: number
}
